### PR TITLE
Fixed null bytes in the magnetometer config file

### PR DESCRIPTION
**Pull request by ron-popov**

### CODE REVIEW

**Review by yotam180 — APPROVED** [review]
איך טאָן ניט באַקומען עס

**Comment by ron-popov** [comment]
@yotam180 מיר אויך

**Comment by ron-popov** [comment]
we should keep the ```hotfixes``` branch for all sorts of small fixes that don't require a new branch (like removing a null byte)

**Comment by yotam180** [comment]
Oh, alright.

**Pull request merged**
