### PR TITLE
Communication

### PR DESCRIPTION
**Pull request by yotam180**
Unsafe error reporting. Will take care of that later.

### CODE REVIEW

**Review by shaiTheKimhi — APPROVED** [review]

**Comment by yotam180** [comment]
thank you very much

**Comment by shaiTheKimhi** [comment]
why is the module automatically creates connection and sends a message?

**Comment by shaiTheKimhi** [comment]
@yotam180

**Comment by yotam180** [comment]
Why don't you read my answer at #29, @shaiTheKimhi?

**Comment by shaiTheKimhi** [comment]
I didn't saw the answer and thought you would see it better here.

**Pull request merged**
